import React, { useState, useEffect } from 'react';
import { useNavigate } from 'react-router-dom';
import './AdaptiveQuizzes.css'; // Reuse the same styles

const API_BASE_URL =
  process.env.REACT_APP_API_URL ||
  (window.location.hostname === 'localhost' ? 'http://localhost:5000' : window.location.origin);

function LevelQuizzes() {
  const navigate = useNavigate();
  const [quizzes, setQuizzes] = useState([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState('');
  const [placementCompleted, setPlacementCompleted] = useState(false);

  useEffect(() => {
    checkPlacementAndFetchQuizzes();
  }, []);

  const getToken = () => localStorage.getItem('token');

  const checkPlacementAndFetchQuizzes = async () => {
    try {
      // First check if placement quiz is completed
      const placementRes = await fetch(`${API_BASE_URL}/api/student/placement-status`, {
        headers: { 'Authorization': `Bearer ${getToken()}` }
      });

      const placementData = await placementRes.json();
      
      if (!placementData.success || !placementData.placementCompleted) {
        setPlacementCompleted(false);
        setError('You must complete the placement quiz first!');
        setLoading(false);
        return;
      }

      setPlacementCompleted(true);

      // Fetch level-based quizzes
      const quizzesRes = await fetch(`${API_BASE_URL}/api/adaptive-quiz/level-quizzes`, {
        headers: { 'Authorization': `Bearer ${getToken()}` }
      });

      const quizzesData = await quizzesRes.json();

      if (quizzesData.success) {
        setQuizzes(quizzesData.data || []);
      } else {
        setError('Failed to load quizzes');
      }
    } catch (error) {
      console.error('Failed to fetch data:', error);
      setError('Failed to load quizzes');
    } finally {
      setLoading(false);
    }
  };

  const startQuiz = (quizId) => {
    navigate(`/student/adaptive-quiz/${quizId}`);
  };

  if (loading) {
    return (
      <div className="adaptive-quizzes-container">
        <div className="loading">Loading quizzes...</div>
      </div>
    );
  }

  // Show message if placement not completed
  if (!placementCompleted) {
    return (
      <div className="adaptive-quizzes-container">
        <header className="page-header">
          <div>
            <h1>🎯 Level Quizzes</h1>
            <p className="page-subtitle">Complete the placement quiz first to unlock level-based quizzes</p>
          </div>
          <button 
            className="btn-back"
            onClick={() => navigate('/student')}
          >
            ← Back to Dashboard
          </button>
        </header>

        <div className="error-message">
          {error}
          <div style={{ marginTop: '20px' }}>
            <button 
              className="btn-start-quiz"
              onClick={() => navigate('/student/quiz/placement')}
            >
              Go to Placement Quiz
            </button>
          </div>
        </div>
      </div>
    );
  }

  return (
    <div className="adaptive-quizzes-container">
      <header className="page-header">
        <div>
          <h1>🎯 Level Quizzes (1-10)</h1>
          <p className="page-subtitle">Progress through 10 levels of mathematics mastery</p>
        </div>
        <button 
          className="btn-back"
          onClick={() => navigate('/student')}
        >
          ← Back to Dashboard
        </button>
      </header>

      {error && <div className="error-message">{error}</div>}

      <div className="quizzes-grid">
          {quizzes.length === 0 ? (
            <div className="no-data">
              <div className="no-data-icon">📝</div>
              <p>No level quizzes available yet.</p>
              <p style={{ fontSize: '14px', color: '#6b7280', marginTop: '8px' }}>
                Level quizzes are auto-generated by the system. Please contact your administrator if you don't see any quizzes.
              </p>
            </div>
          ) : (
            quizzes.map((quiz) => (
              <div key={quiz._id} className="quiz-card">
                <div className="quiz-card-header">
                  <h3>{quiz.title}</h3>
                  <span className="quiz-badge level-badge" style={{ 
                    background: 'linear-gradient(135deg, #667eea 0%, #764ba2 100%)',
                    color: '#fff'
                  }}>
                    Level {quiz.quiz_level}
                  </span>
                </div>

                <p className="quiz-description">
                  {quiz.description || `Progress through Level ${quiz.quiz_level} mathematics challenges`}
                </p>

                <div className="quiz-stats">
                  <div className="stat-item">
                    <span className="stat-icon">📚</span>
                    <span className="stat-text">
                      {quiz.total_questions} questions
                    </span>
                  </div>
                  <div className="stat-item">
                    <span className="stat-icon">✨</span>
                    <span className="stat-text">
                      Auto-generated
                    </span>
                  </div>
                </div>

                <div className="difficulty-distribution">
                  <div className="distribution-label">Difficulty Levels:</div>
                  <div className="distribution-bars">
                    {Object.entries(quiz.difficulty_distribution || {}).map(([level, count]) => (
                      count > 0 && (
                        <div key={level} className="distribution-bar">
                          <span className={`level-indicator level-${level}`}>
                            D{level}
                          </span>
                          <span className="count">{count}</span>
                        </div>
                      )
                    ))}
                  </div>
                </div>

                <button 
                  className="btn-start-quiz"
                  onClick={() => startQuiz(quiz._id)}
                  style={{
                    background: 'linear-gradient(135deg, #667eea 0%, #764ba2 100%)',
                    color: '#fff'
                  }}
                >
                  Start Level {quiz.quiz_level} Quiz
                </button>
              </div>
            ))
          )}
      </div>
    </div>
  );
}

export default LevelQuizzes;
